---
swagger: "2.0"
info:
  version: "0.1"
  title: "EMF_Server_Controller"
consumes:
- "application/json"
produces:
- "application/json"
paths:
  /:
    get:
      tags:
      - "emf_server"
      summary: "Hello World!"
      operationId: "application_hello_world"
      parameters: []
      responses:
        200:
          description: "OK"
      x-swagger-router-controller: "swagger_server.controllers.emf_server_controller"
  /app:
    get:
      tags:
      - "emf_server"
      summary: "Gets information about all applications"
      operationId: "application_get_all_apps"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters: []
      responses:
        200:
          description: "OK."
          schema:
            $ref: "#/definitions/ArrayOfApps"
        400:
          description: "Bad request."
        404:
          description: "Not found."
        500:
          description: "Internal server error."
      x-swagger-router-controller: "swagger_server.controllers.emf_server_controller"
  /app/{appID}:
    get:
      tags:
      - "emf_server"
      summary: "Gets information about a specific application"
      operationId: "application_get_app"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - name: "appID"
        in: "path"
        description: "ID of the application to get information"
        required: true
        type: "integer"
        format: "int64"
      responses:
        200:
          description: "OK."
          schema:
            $ref: "#/definitions/AppTotalInfo"
        400:
          description: "Bad request."
        404:
          description: "Not found."
        500:
          description: "Internal server error."
      x-swagger-router-controller: "swagger_server.controllers.emf_server_controller"
    post:
      tags:
      - "emf_server"
      summary: "Stop an application"
      operationId: "application_stop_app"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - name: "appID"
        in: "path"
        description: "ID of the application to stop"
        required: true
        type: "integer"
        format: "int64"
      responses:
        200:
          description: "OK."
          schema:
            $ref: "#/definitions/AppInfo"
        400:
          description: "Bad request."
        404:
          description: "Not found."
        500:
          description: "Internal server error."
      x-swagger-router-controller: "swagger_server.controllers.emf_server_controller"
    delete:
      tags:
      - "emf_server"
      summary: "Removes an application from the platform"
      operationId: "application_delete_app"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - name: "appID"
        in: "path"
        description: "ID of the application to remove"
        required: true
        type: "integer"
        format: "int64"
      responses:
        200:
          description: "OK."
          schema:
            $ref: "#/definitions/AppInfo"
        400:
          description: "Bad request."
        404:
          description: "Not found."
        500:
          description: "Internal server error."
      x-swagger-router-controller: "swagger_server.controllers.emf_server_controller"
  /app/deploy:
    post:
      tags:
      - "emf_server"
      summary: "Deploy App"
      operationId: "application_deploy_app"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "Application object to be deployed"
        required: true
        schema:
          $ref: "#/definitions/AppDeploy"
      responses:
        201:
          description: "Created."
          schema:
            $ref: "#/definitions/AppTotalInfo"
        400:
          description: "Bad request."
        500:
          description: "Internal server error"
      x-swagger-router-controller: "swagger_server.controllers.emf_server_controller"
  /app/tracing/{appID}:
    get:
      tags:
      - "emf_server"
      summary: "Gets information about tracing of a specific application"
      operationId: "application_get_app_tracing"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - name: "appID"
        in: "path"
        description: "ID of the application"
        required: true
        type: "integer"
        format: "int64"
      responses:
        200:
          description: "OK."
          schema:
            type: "string"
            example: "127.0.0.1:8080"
        400:
          description: "Bad request."
        404:
          description: "Not found."
        500:
          description: "Internal server error."
      x-swagger-router-controller: "swagger_server.controllers.emf_server_controller"
definitions:
  AppDeploy:
    type: "object"
    required:
    - "docker_image"
    - "name"
    - "quality_metrics"
    properties:
      name:
        type: "string"
        example: "Songs Application"
        description: "Name of the application to be deployed"
      docker_image:
        type: "string"
        example: "fcribeiro/Songs_MS"
        description: "Name of the docker image"
      quality_metrics:
        type: "array"
        items:
          $ref: "#/definitions/QualityMetrics"
    example:
      quality_metrics:
      - metric: "metric"
        value: "value"
      - metric: "metric"
        value: "value"
      name: "Songs Application"
      docker_image: "fcribeiro/Songs_MS"
  AppTotalInfo:
    type: "object"
    required:
    - "docker_image"
    - "id"
    - "name"
    - "quality_metrics"
    - "state"
    properties:
      id:
        type: "integer"
        example: 1
        description: "The application ID."
      name:
        type: "string"
        example: "Songs Application"
        description: "Name of the deployed application"
      state:
        type: "string"
        example: "Running"
        description: "Current state of the application"
      docker_image:
        type: "string"
        example: "fcribeiro/Songs_MS"
        description: "Name of the docker image"
      quality_metrics:
        type: "array"
        items:
          $ref: "#/definitions/QualityMetrics"
    example:
      quality_metrics:
      - metric: "metric"
        value: "value"
      - metric: "metric"
        value: "value"
      name: "Songs Application"
      id: 1
      state: "Running"
      docker_image: "fcribeiro/Songs_MS"
  AppInfo:
    type: "object"
    required:
    - "id"
    - "name"
    - "state"
    properties:
      id:
        type: "integer"
        example: 1
        description: "The application ID."
      name:
        type: "string"
        example: "Songs Application"
        description: "Name of the deployed application"
      state:
        type: "string"
        example: "Stopped"
        description: "Current state of the application"
    example:
      name: "Songs Application"
      id: 1
      state: "Stopped"
  ArrayOfApps:
    type: "array"
    items:
      $ref: "#/definitions/AppInfo"
  QualityMetrics:
    type: "object"
    properties:
      metric:
        type: "string"
      value:
        type: "string"
    example:
      metric: "metric"
      value: "value"
